name: congrats
description: Congrats someone on completing the challenge
author: Kira272921
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  label:
    description: Name of the label
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: anchor
  color: green
