on:
  issues:
    types: [labeled]

jobs:
  congrats:
    runs-on: ubuntu-latest
    steps:
      - name: congrats
        uses: ../../src/packages/github-action/
        with:
          label: submission
